#!/usr/bin/env bash
set -euo pipefail

# Tesla P40 / Pascal is safer with fp16 than bf16.
python sequential_matrix_cells_speechcommands_v13_categorized_signal_bus_builder.py \
  --data-root ./data/speechcommands \
  --device cuda \
  --amp fp16 \
  --classes yes,no,up,down,left,right,on,off,stop,go \
  --train-limit 12000 \
  --val-limit 2000 \
  --batch-size 128 \
  --eval-batch-size 256 \
  --workers 4 \
  --pin-memory \
  --dim 128 \
  --n-mels 64 \
  --hop-length 160 \
  --evidence-cells 48 \
  --topology grid \
  --num-layers 4 \
  --blocks-per-layer 4 \
  --skip-mode on \
  --block-cells 2 \
  --global-cells 3 \
  --memory-cells 6 \
  --gate-floor 0.15 \
  --late-gate-floor 0.25 \
  --late-gate-floor-end 0.15 \
  --late-gate-floor-decay-start 5 \
  --late-gate-floor-decay-epochs 8 \
  --late-write-target 0.35 \
  --late-dyn-gate-target 0.15 \
  --weak-class-late-read-target 0.35 \
  --role-signal-scale 0.35 \
  --signal-op-bias-scale 0.20 \
  --category-temp 1.0 \
  --primitive-temp 1.0 \
  --lock-last-role \
  --stage-gate-bias-init 1.0 \
  --class-stage-bias-std 0.35 \
  --task-attn-temp 0.85 \
  --evidence-attn-temp 1.0 \
  --operator-temp 1.25 \
  --evidence-dropout 0.10 \
  --lr 7e-4 \
  --lr-scheduler cosine \
  --warmup-epochs 2 \
  --min-lr-ratio 0.15 \
  --grad-clip 0.7 \
  --lambda-read-entropy 0.0 \
  --lambda-read-diversity 0.04 \
  --lambda-stage-load-balance 0.004 \
  --lambda-evidence-source-balance 0.02 \
  --lambda-operator-balance 0.02 \
  --lambda-global-diversity 0.008 \
  --lambda-memory-diversity 0.004 \
  --lambda-operator-entropy-per-block 0.003 \
  --lambda-block-diversity 0.020 \
  --lambda-route-diversity 0.010 \
  --lambda-adapter-diversity 0.008 \
  --lambda-phase-role 0.020 \
  --lambda-global-skip-penalty 0.004 \
  --lambda-late-write 0.015 \
  --lambda-late-dyn-gate 0.010 \
  --lambda-weak-class-late-read 0.020 \
  --lambda-role-diversity 0.006 \
  --lambda-role-anchor 0.010 \
  --lambda-category-diversity 0.006 \
  --lambda-category-entropy 0.002 \
  --decomp-every 25 \
  --speed-log \
  --epochs 15 \
  --out-dir ./runs/v13_categorized_signal_bus_builder_15ep
